=== RushuiGuan/codegen/Test.Client/codegen-settings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CSharpWebClientSettings",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "controllerFilters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SymbolFilterPatterns"
      }
    },
    "controllerMethodFilters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SymbolFilterPatterns"
      }
    },
    "dtoEnumFilters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SymbolFilterPatterns"
      }
    },
    "namespace": {
      "type": "string"
    },
    "useInterface": {
      "type": "boolean"
    },
    "useInternalProxy": {
      "type": "boolean"
    },
    "constructorSettings": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/WebClientConstructorSettings"
      }
    },
    "customTypeMapping": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "SymbolFilterPatterns": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "exclude": {
          "type": [
            "null",
            "string"
          ]
        },
        "include": {
          "type": [
            "null",
            "string"
          ]
        },
        "hasValue": {
          "type": "boolean"
        }
      }
    },
    "WebClientConstructorSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "compressionEncoding": {
          "type": [
            "null",
            "string"
          ]
        },
        "omit": {
          "type": "boolean"
        },
        "customJsonSettings": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== RushuiGuan/codegen/Test.Client/codegen-settings.json
{
  "$schema": "codegen-settings.schema.json",
  "namespace": "Test.Client",
  "useInterface": false,
  "constructorSettings": {
    "OmittedConstructorController": {
      "omit": true
    },
    "CustomJsonSettingsController": {
      "customJsonSettings": "MyCustomJsonSettings.Options"
    }
  },
  "controllerFilters": [
    {
      "exclude": "^Test\\.WebApi\\.Controllers\\.(AbsUrl)?RedirectTestController$"
    },
    {
      "exclude": "FilteredController$"
    }
  ],
  "controllerMethodFilters": [
    {
      "exclude": "FilteredByAll$"
    }
  ],
  "customTypeMapping": {
    "Test.WebApi.Controllers.EntityName":"string"
  }
}

=== RushuiGuan/codegen/Test.WithInterface.Client/codegen-settings.json
{
  "$schema": "codegen-settings.schema.json",
  "namespace": "Test.WithInterface.Client",
  "useInterface": true,
  "useInternalProxy": false,
  "constructorSettings": {
    "OmittedConstructorController": {
      "omit": true
    },
    "CustomJsonSettingsController": {
      "customJsonSettings": "MyCustomJsonSettings.Options"
    }
  },
  "controllerFilters": [
    {
      "exclude": "^Test\\.WebApi\\.Controllers\\.(AbsUrl)?RedirectTestController$"
    },
    {
      "exclude": "FilteredController$"
    }
  ],
  "controllerMethodFilters": [
    {
      "exclude": "FilteredByAll$"
    }
  ],
  "customTypeMapping": {
    "Test.WebApi.Controllers.EntityName": "string"
  }
}
